### ISSUE TITLE
Ordering?

### ISSUE THREAD

**Issue by 0rangeMan** [cludden/s3-kinesis-replay#3]
Hi,
Thanks for the great project.
Just wondering how the messages are written to kinesis, w.r.t.
When you have multiple files in the S3 bucket, in which order the data in the files will be written to kinesis?

**Comment by cludden** [comment]
@0rangeMan just saw this, sorry for the delay. with `concurrency` of 1, files are downloaded and written in bucket listing order, anything over 1 will lose any particular ordering guarantees
